### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by m-h-asfour** [dex-os/DexOS#1]
hextest.exe contains a virus

**Comment by bubach** [comment]
No it does not.

**Comment by m-h-asfour** [comment]
I am an ex-computer engineer in Egypt. My past experience was trying to assist companies and a bank to make applications. That was about a quarter of a century ago and mainly on machines that they called "mainframes", and of course that had nothing to do with viruses. Now I'm just a very shallow "normal" user and despite this fact, I can hardly bear being forced to use more of such machines and such software. I have Avira antivirus (free edition of course) installed together with Microsoft security essentials and what remained from "Hitman" after his successful mission and the end of the free period. I downloaded DexOs zip file, and tried to unzip it using 7zip. It used to hang when it reaches hextext.exe, then Avira started to generate an increasing number of alerts for viruses that exceed its limit for the free edition, while Microsoft essentials used to display a message saying "no action needed". I tried to just unpack the zip more than once and every time I had to turn off the PC during this process. Apparently it was some sort of a loop, and every time no more alerts were generated after the reboot until I retry to unzip. I faced the same situation even when I tried to unzip the newly downloaded zipped file that github created from your repository.  Now, after the removal of this EXE, the zip file was unzipped successfully without any alerts at all. So, although I do not consider myself an expert in viruses, I have every very convincing reason to believe that hextest.exe is the "problem". I still did not even try to use DexOs yet and I still do not know how important is that EXE file for it, but please try to do something if you can.
